### ISSUE TITLE
Understanding Convolution Implementation

### ISSUE THREAD

**Issue by jon-chuang** [IntelAI/he-transformer#12]
I am trying to understand how the memory allocations are performed. 
Specifically, why is there a line 
`seal::MemoryPoolHandle pool = seal::MemoryPoolHandle::ThreadLocal()`
defined in `seal/kernel/convolution_seal.cpp`? This pool is never utilised. Is this just an artifact?

**Comment by fboemer** [comment]
Thanks for pointing this out; it is a remnant from a prior implementation and has now been removed.

**Comment by jon-chuang** [comment]
Hi @fboemer 
Thanks. Can I ask why the global pool is used instead of a thread local pool? Does this not slow down performance due to resource contention? Could this be why the ngraph-HE multithreaded Cryptonets performance plateaus at roughly 24 threads?

**Comment by fboemer** [comment]
We weren't seeing any speedup when we tried thread-local mempools. 

The Cryptonets performance is primarily spent in the convolution and FC layers, which use cipher-plaintext multiplication and ciphertext-ciphertext addition, neither of which use the pool for CKKS (https://github.com/microsoft/SEAL/blob/9fc376c19488be2bfd213780ee06789754f4b2c2/native/src/seal/evaluator.cpp#L1880-L1887 
 ; https://github.com/microsoft/SEAL/blob/9fc376c19488be2bfd213780ee06789754f4b2c2/native/src/seal/evaluator.cpp#L98). Perhaps some improvement can be made during rescaling, or ciphertext-ciphertext multiplication, which use the pool.

**Comment by jon-chuang** [comment]
Dear Fabian,

Actually, I believe there are allocations performed by multiplication as can be seen in `ckks_multiply` and other multiplications in https://github.com/microsoft/SEAL/blob/master/native/src/seal/evaluator.cpp.

These are the function calls used in https://github.com/IntelAI/he-transformer/blob/master/src/seal/kernel/multiply_seal.cpp.

**Comment by jon-chuang** [comment]
From what I understand then, rescaling isn't used either because the ciphertext is refreshed at every layer?

**Comment by fboemer** [comment]
We refresh the ciphertexts for non-polynomial activations such as ReLU using a decrypt-(send to client)-relu-encrypt-(send to server). Independently, rescaling is used after a multiplication layer such as Convolution or Dot. Rescaling has a small runtime compared to the Convolution/Dot layer itself, so the use of local thread pools is less performance-critical
