### ISSUE TITLE
 Build failure because of the 'ext_protobuf' extension

### ISSUE THREAD

**Issue by mlayou** [IntelAI/he-transformer#37]
I got the following error while building the he-transformer. It seems to affect the `'ext_protobuf'` extension. Any suggestions on how to fix it. 

```
user1@ubuntu:~/nGraph/he-transformer/build$ make install
[  5%] Built target ext_ngraph
[  9%] Built target ext_zlib
[ 13%] Built target ext_ngraph_tf
[ 18%] Built target ext_seal
[ 18%] Performing configure step for 'ext_protobuf'
+ mkdir -p third_party/googletest/m4
+ autoreconf -f -i -Wall,no-obsolete
./autogen.sh: 37: ./autogen.sh: autoreconf: not found
CMakeFiles/ext_protobuf.dir/build.make:107: recipe for target 'protobuf/stamp/ext_protobuf-configure' failed
make[2]: *** [protobuf/stamp/ext_protobuf-configure] Error 127
CMakeFiles/Makefile2:194: recipe for target 'CMakeFiles/ext_protobuf.dir/all' failed
make[1]: *** [CMakeFiles/ext_protobuf.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

I have tried to ignore the problem above, but it's preventing the examples from running. 
I get the same error when using the `--backend=HE_SEAL` option.
```
(venv-tf-py3) user1@ubuntu:~/nGraph/he-transformer$ python examples/ax.py --backend=CPU
[...]
config graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
    min_graph_nodes: -1
    custom_optimizers {
      name: "ngraph-optimizer"
      parameter_map {
        key: "device_id"
        value {
          s: ""
        }
      }
      parameter_map {
        key: "enable_client"
        value {
          s: "False"
        }
      }
      parameter_map {
        key: "encryption_parameters"
        value {
          s: ""
        }
      }
      parameter_map {
        key: "ngraph_backend"
        value {
          s: "CPU"
        }
      }
    }
  }
}

2020-03-29 19:39:10.337638: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2496085000 Hz
2020-03-29 19:39:10.339407: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x29fc300 executing computations on platform Host. Devices:
2020-03-29 19:39:10.339488: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-03-29 19:39:10.346982: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] NgraphOptimizer failed: Internal: Could not create backend of type CPU. Got exception: Unable to find backend 'CPU' as file '/home/user1/nGraph/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.6/site-packages/ngraph_bridge/libcpu_backend.so'
Open error message '/home/user1/nGraph/he-transformer/build/ext_ngraph_tf/src/ext_ngraph_tf/build_cmake/venv-tf-py3/lib/python3.6/site-packages/ngraph_bridge/libmklml_intel.so: cannot read file data'
2020-03-29 19:39:10.347551: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Result:  [[2. 3. 4. 5.]]

```

**Comment by fboemer** [comment]
Our build instructions are probably missing some dependencies. Take a look [here](https://github.com/horst3180/arc-theme/issues/63) or [here](https://github.com/IntelAI/he-transformer/blob/master/contrib/docker/Dockerfile.he_transformer.ubuntu1804#L25-L38)

**Comment by mlayou** [comment]
> Our build instructions are probably missing some dependencies. Take a look [here](https://github.com/horst3180/arc-theme/issues/63) or [here](https://github.com/IntelAI/he-transformer/blob/master/contrib/docker/Dockerfile.he_transformer.ubuntu1804#L25-L38)

Thanks for the pointers. I have installed those dependencies, and resumed the build. It's still running. I'll report back on how it went when it's done.

**Comment by mlayou** [comment]
Hello again,

The build for the 'protobuf' extension gets stuck (see the logs below). Do I have to rebuild the whole project again from scratch? 

Another question: the build process as defined now is quite extensive and _**seems**_ to include so many things that may not be needed by everyone. Is there a subset of targets in the Makefile that would be sufficient to build in order to run/develop programs similar to the examples that come with he-transformer library? 

```
user1@ubuntu:~/nGraph/he-transformer/build$ make -j install
[  5%] Built target ext_boost
[  9%] Built target pybind11
[ 13%] Built target ext_gtest
[ 17%] Built target ext_zlib
[ 22%] Built target ext_json
[ 26%] Built target ext_ngraph_tf
[ 32%] Performing build step for 'ext_protobuf'
[ 31%] Built target ext_seal
[ 37%] Built target ext_ngraph
[ 41%] Built target ext_abseil
Making all in .
Making all in src
  CXX      google/protobuf/stubs/bytestream.lo
  CXX      google/protobuf/stubs/common.lo
  CXX      google/protobuf/stubs/int128.lo
  CXX      google/protobuf/stubs/status.lo
  CXX      google/protobuf/stubs/stringpiece.lo
  CXX      google/protobuf/stubs/stringprintf.lo
  [...]
  CXX      google/protobuf/compiler/csharp/csharp_reflection_class.lo
  CXX      google/protobuf/compiler/csharp/csharp_source_generator_base.lo
  CXX      google/protobuf/compiler/main.o
  CXX      google/protobuf/compiler/csharp/csharp_wrapper_field.lo

```

And below is the full log trace.

```
user1@ubuntu:~/nGraph/he-transformer/build$ make -j install
[  5%] Built target ext_boost
[  9%] Built target pybind11
[ 13%] Built target ext_gtest
[ 17%] Built target ext_zlib
[ 22%] Built target ext_json
[ 26%] Built target ext_ngraph_tf
[ 32%] Performing build step for 'ext_protobuf'
[ 31%] Built target ext_seal
[ 37%] Built target ext_ngraph
[ 41%] Built target ext_abseil
Making all in .
Making all in src
  CXX      google/protobuf/stubs/bytestream.lo
  CXX      google/protobuf/stubs/common.lo
  CXX      google/protobuf/stubs/int128.lo
  CXX      google/protobuf/stubs/status.lo
  CXX      google/protobuf/stubs/stringpiece.lo
  CXX      google/protobuf/stubs/stringprintf.lo
  CXX      google/protobuf/stubs/structurally_valid.lo
  CXX      google/protobuf/stubs/strutil.lo
  CXX      google/protobuf/stubs/time.lo
  CXX      google/protobuf/any_lite.lo
  CXX      google/protobuf/arena.lo
  CXX      google/protobuf/stubs/statusor.lo
  CXX      google/protobuf/generated_enum_util.lo
  CXX      google/protobuf/extension_set.lo
  CXX      google/protobuf/implicit_weak_message.lo
  CXX      google/protobuf/repeated_field.lo
  CXX      google/protobuf/message_lite.lo
  CXX      google/protobuf/parse_context.lo
  CXX      google/protobuf/io/strtod.lo
  CXX      google/protobuf/io/zero_copy_stream.lo
  CXX      google/protobuf/io/zero_copy_stream_impl_lite.lo
  CXX      google/protobuf/io/zero_copy_stream_impl.lo
  CXX      google/protobuf/generated_message_util.lo
  CXX      google/protobuf/io/coded_stream.lo
  CXX      google/protobuf/generated_message_table_driven_lite.lo
  CXX      google/protobuf/wire_format_lite.lo
  CXX      google/protobuf/any.lo
  CXX      google/protobuf/descriptor.lo
  CXX      google/protobuf/any.pb.lo
  CXX      google/protobuf/stubs/mathlimits.lo
  CXX      google/protobuf/descriptor_database.lo
  CXX      google/protobuf/api.pb.lo
  CXX      google/protobuf/duration.pb.lo
  CXX      google/protobuf/dynamic_message.lo
  CXX      google/protobuf/descriptor.pb.lo
  CXX      google/protobuf/empty.pb.lo
  CXX      google/protobuf/extension_set_heavy.lo
  CXX      google/protobuf/field_mask.pb.lo
  CXX      google/protobuf/generated_message_table_driven.lo
  CXX      google/protobuf/generated_message_reflection.lo
  CXX      google/protobuf/map_field.lo
  CXX      google/protobuf/message.lo
  CXX      google/protobuf/service.lo
  CXX      google/protobuf/reflection_ops.lo
  CXX      google/protobuf/struct.pb.lo
  CXX      google/protobuf/source_context.pb.lo
  CXX      google/protobuf/type.pb.lo
  CXX      google/protobuf/stubs/substitute.lo
  CXX      google/protobuf/text_format.lo
  CXX      google/protobuf/unknown_field_set.lo
  CXX      google/protobuf/timestamp.pb.lo
  CXX      google/protobuf/wire_format.lo
  CXX      google/protobuf/io/gzip_stream.lo
  CXX      google/protobuf/io/printer.lo
  CXX      google/protobuf/compiler/importer.lo
  CXX      google/protobuf/io/tokenizer.lo
  CXX      google/protobuf/wrappers.pb.lo
  CXX      google/protobuf/util/delimited_message_util.lo
  CXX      google/protobuf/compiler/parser.lo
  CXX      google/protobuf/util/field_mask_util.lo
  CXX      google/protobuf/util/field_comparator.lo
  CXX      google/protobuf/util/internal/default_value_objectwriter.lo
  CXX      google/protobuf/util/internal/datapiece.lo
  CXX      google/protobuf/util/internal/error_listener.lo
  CXX      google/protobuf/util/internal/field_mask_utility.lo
  CXX      google/protobuf/util/internal/json_escaping.lo
  CXX      google/protobuf/util/internal/object_writer.lo
  CXX      google/protobuf/util/internal/json_stream_parser.lo
  CXX      google/protobuf/util/internal/json_objectwriter.lo
  CXX      google/protobuf/util/internal/protostream_objectsource.lo
  CXX      google/protobuf/util/internal/proto_writer.lo
  CXX      google/protobuf/util/internal/protostream_objectwriter.lo
  CXX      google/protobuf/util/internal/type_info.lo
  CXX      google/protobuf/util/internal/type_info_test_helper.lo
  CXX      google/protobuf/util/internal/utility.lo
  CXX      google/protobuf/util/message_differencer.lo
  CXX      google/protobuf/util/json_util.lo
  CXX      google/protobuf/util/time_util.lo
  CXX      google/protobuf/util/type_resolver_util.lo
  CXX      google/protobuf/compiler/command_line_interface.lo
  CXX      google/protobuf/compiler/code_generator.lo
  CXX      google/protobuf/compiler/plugin.pb.lo
  CXX      google/protobuf/compiler/plugin.lo
  CXX      google/protobuf/compiler/zip_writer.lo
  CXX      google/protobuf/compiler/cpp/cpp_enum.lo
  CXX      google/protobuf/compiler/subprocess.lo
  CXX      google/protobuf/compiler/cpp/cpp_enum_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_generator.lo
  CXX      google/protobuf/compiler/cpp/cpp_file.lo
  CXX      google/protobuf/compiler/cpp/cpp_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_extension.lo
  CXX      google/protobuf/compiler/cpp/cpp_map_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_helpers.lo
  CXX      google/protobuf/compiler/cpp/cpp_message_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_padding_optimizer.lo
  CXX      google/protobuf/compiler/cpp/cpp_primitive_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_service.lo
  CXX      google/protobuf/compiler/cpp/cpp_string_field.lo
  CXX      google/protobuf/compiler/cpp/cpp_message.lo
  CXX      google/protobuf/compiler/java/java_enum_field.lo
  CXX      google/protobuf/compiler/java/java_enum.lo
  CXX      google/protobuf/compiler/java/java_enum_lite.lo
  CXX      google/protobuf/compiler/java/java_context.lo
  CXX      google/protobuf/compiler/java/java_enum_field_lite.lo
  CXX      google/protobuf/compiler/java/java_extension.lo
  CXX      google/protobuf/compiler/java/java_generator_factory.lo
  CXX      google/protobuf/compiler/java/java_file.lo
  CXX      google/protobuf/compiler/java/java_extension_lite.lo
  CXX      google/protobuf/compiler/java/java_generator.lo
  CXX      google/protobuf/compiler/java/java_field.lo
  CXX      google/protobuf/compiler/java/java_helpers.lo
  CXX      google/protobuf/compiler/java/java_map_field.lo
  CXX      google/protobuf/compiler/java/java_map_field_lite.lo
  CXX      google/protobuf/compiler/java/java_message.lo
  CXX      google/protobuf/compiler/java/java_message_lite.lo
  CXX      google/protobuf/compiler/java/java_message_builder.lo
  CXX      google/protobuf/compiler/java/java_message_field_lite.lo
  CXX      google/protobuf/compiler/java/java_name_resolver.lo
  CXX      google/protobuf/compiler/java/java_message_field.lo
  CXX      google/protobuf/compiler/java/java_message_builder_lite.lo
  CXX      google/protobuf/compiler/java/java_primitive_field.lo
  CXX      google/protobuf/compiler/java/java_shared_code_generator.lo
  CXX      google/protobuf/compiler/java/java_primitive_field_lite.lo
  CXX      google/protobuf/compiler/java/java_service.lo
  CXX      google/protobuf/compiler/java/java_string_field.lo
  CXX      google/protobuf/compiler/java/java_doc_comment.lo
  CXX      google/protobuf/compiler/java/java_string_field_lite.lo
  CXX      google/protobuf/compiler/js/js_generator.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_enum.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_enum_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_extension.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_file.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_helpers.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_message.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_generator.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_map_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_message_field.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_oneof.lo
  CXX      google/protobuf/compiler/objectivec/objectivec_primitive_field.lo
  CXX      google/protobuf/compiler/python/python_generator.lo
  CXX      google/protobuf/compiler/csharp/csharp_doc_comment.lo
  CXX      google/protobuf/compiler/ruby/ruby_generator.lo
  CXX      google/protobuf/compiler/csharp/csharp_enum_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_enum.lo
  CXX      google/protobuf/compiler/php/php_generator.lo
  CXX      google/protobuf/compiler/csharp/csharp_helpers.lo
  CXX      google/protobuf/compiler/csharp/csharp_generator.lo
  CXX      google/protobuf/compiler/csharp/csharp_field_base.lo
  CXX      google/protobuf/compiler/csharp/csharp_map_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_message.lo
  CXX      google/protobuf/compiler/csharp/csharp_message_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_primitive_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_repeated_primitive_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_repeated_message_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_repeated_enum_field.lo
  CXX      google/protobuf/compiler/csharp/csharp_reflection_class.lo
  CXX      google/protobuf/compiler/csharp/csharp_source_generator_base.lo
  CXX      google/protobuf/compiler/main.o
  CXX      google/protobuf/compiler/csharp/csharp_wrapper_field.lo

```

**Comment by fboemer** [comment]
> Hello again,
> 
> The build for the 'protobuf' extension gets stuck (see the logs below). Do I have to rebuild the whole project again from scratch?
> 
> Another question: the build process as defined now is quite extensive and _**seems**_ to include so many things that may not be needed by everyone. Is there a subset of targets in the Makefile that would be sufficient to build in order to run/develop programs similar to the examples that come with he-transformer library?
> 
> ```
> user1@ubuntu:~/nGraph/he-transformer/build$ make -j install
> [  5%] Built target ext_boost
> [  9%] Built target pybind11
> [ 13%] Built target ext_gtest
> [ 17%] Built target ext_zlib
> [ 22%] Built target ext_json
> [ 26%] Built target ext_ngraph_tf
> [ 32%] Performing build step for 'ext_protobuf'
> [ 31%] Built target ext_seal
> [ 37%] Built target ext_ngraph
> [ 41%] Built target ext_abseil
> Making all in .
> Making all in src
>   CXX      google/protobuf/stubs/bytestream.lo
>   CXX      google/protobuf/stubs/common.lo
>   CXX      google/protobuf/stubs/int128.lo
>   CXX      google/protobuf/stubs/status.lo
>   CXX      google/protobuf/stubs/stringpiece.lo
>   CXX      google/protobuf/stubs/stringprintf.lo
>   [...]
>   CXX      google/protobuf/compiler/csharp/csharp_reflection_class.lo
>   CXX      google/protobuf/compiler/csharp/csharp_source_generator_base.lo
>   CXX      google/protobuf/compiler/main.o
>   CXX      google/protobuf/compiler/csharp/csharp_wrapper_field.lo
> ```
> 
> And below is the full log trace.
> 
> ```
> user1@ubuntu:~/nGraph/he-transformer/build$ make -j install
> [  5%] Built target ext_boost
> [  9%] Built target pybind11
> [ 13%] Built target ext_gtest
> [ 17%] Built target ext_zlib
> [ 22%] Built target ext_json
> [ 26%] Built target ext_ngraph_tf
> [ 32%] Performing build step for 'ext_protobuf'
> [ 31%] Built target ext_seal
> [ 37%] Built target ext_ngraph
> [ 41%] Built target ext_abseil
> Making all in .
> Making all in src
>   CXX      google/protobuf/stubs/bytestream.lo
>   CXX      google/protobuf/stubs/common.lo
>   CXX      google/protobuf/stubs/int128.lo
>   CXX      google/protobuf/stubs/status.lo
>   CXX      google/protobuf/stubs/stringpiece.lo
>   CXX      google/protobuf/stubs/stringprintf.lo
>   CXX      google/protobuf/stubs/structurally_valid.lo
>   CXX      google/protobuf/stubs/strutil.lo
>   CXX      google/protobuf/stubs/time.lo
>   CXX      google/protobuf/any_lite.lo
>   CXX      google/protobuf/arena.lo
>   CXX      google/protobuf/stubs/statusor.lo
>   CXX      google/protobuf/generated_enum_util.lo
>   CXX      google/protobuf/extension_set.lo
>   CXX      google/protobuf/implicit_weak_message.lo
>   CXX      google/protobuf/repeated_field.lo
>   CXX      google/protobuf/message_lite.lo
>   CXX      google/protobuf/parse_context.lo
>   CXX      google/protobuf/io/strtod.lo
>   CXX      google/protobuf/io/zero_copy_stream.lo
>   CXX      google/protobuf/io/zero_copy_stream_impl_lite.lo
>   CXX      google/protobuf/io/zero_copy_stream_impl.lo
>   CXX      google/protobuf/generated_message_util.lo
>   CXX      google/protobuf/io/coded_stream.lo
>   CXX      google/protobuf/generated_message_table_driven_lite.lo
>   CXX      google/protobuf/wire_format_lite.lo
>   CXX      google/protobuf/any.lo
>   CXX      google/protobuf/descriptor.lo
>   CXX      google/protobuf/any.pb.lo
>   CXX      google/protobuf/stubs/mathlimits.lo
>   CXX      google/protobuf/descriptor_database.lo
>   CXX      google/protobuf/api.pb.lo
>   CXX      google/protobuf/duration.pb.lo
>   CXX      google/protobuf/dynamic_message.lo
>   CXX      google/protobuf/descriptor.pb.lo
>   CXX      google/protobuf/empty.pb.lo
>   CXX      google/protobuf/extension_set_heavy.lo
>   CXX      google/protobuf/field_mask.pb.lo
>   CXX      google/protobuf/generated_message_table_driven.lo
>   CXX      google/protobuf/generated_message_reflection.lo
>   CXX      google/protobuf/map_field.lo
>   CXX      google/protobuf/message.lo
>   CXX      google/protobuf/service.lo
>   CXX      google/protobuf/reflection_ops.lo
>   CXX      google/protobuf/struct.pb.lo
>   CXX      google/protobuf/source_context.pb.lo
>   CXX      google/protobuf/type.pb.lo
>   CXX      google/protobuf/stubs/substitute.lo
>   CXX      google/protobuf/text_format.lo
>   CXX      google/protobuf/unknown_field_set.lo
>   CXX      google/protobuf/timestamp.pb.lo
>   CXX      google/protobuf/wire_format.lo
>   CXX      google/protobuf/io/gzip_stream.lo
>   CXX      google/protobuf/io/printer.lo
>   CXX      google/protobuf/compiler/importer.lo
>   CXX      google/protobuf/io/tokenizer.lo
>   CXX      google/protobuf/wrappers.pb.lo
>   CXX      google/protobuf/util/delimited_message_util.lo
>   CXX      google/protobuf/compiler/parser.lo
>   CXX      google/protobuf/util/field_mask_util.lo
>   CXX      google/protobuf/util/field_comparator.lo
>   CXX      google/protobuf/util/internal/default_value_objectwriter.lo
>   CXX      google/protobuf/util/internal/datapiece.lo
>   CXX      google/protobuf/util/internal/error_listener.lo
>   CXX      google/protobuf/util/internal/field_mask_utility.lo
>   CXX      google/protobuf/util/internal/json_escaping.lo
>   CXX      google/protobuf/util/internal/object_writer.lo
>   CXX      google/protobuf/util/internal/json_stream_parser.lo
>   CXX      google/protobuf/util/internal/json_objectwriter.lo
>   CXX      google/protobuf/util/internal/protostream_objectsource.lo
>   CXX      google/protobuf/util/internal/proto_writer.lo
>   CXX      google/protobuf/util/internal/protostream_objectwriter.lo
>   CXX      google/protobuf/util/internal/type_info.lo
>   CXX      google/protobuf/util/internal/type_info_test_helper.lo
>   CXX      google/protobuf/util/internal/utility.lo
>   CXX      google/protobuf/util/message_differencer.lo
>   CXX      google/protobuf/util/json_util.lo
>   CXX      google/protobuf/util/time_util.lo
>   CXX      google/protobuf/util/type_resolver_util.lo
>   CXX      google/protobuf/compiler/command_line_interface.lo
>   CXX      google/protobuf/compiler/code_generator.lo
>   CXX      google/protobuf/compiler/plugin.pb.lo
>   CXX      google/protobuf/compiler/plugin.lo
>   CXX      google/protobuf/compiler/zip_writer.lo
>   CXX      google/protobuf/compiler/cpp/cpp_enum.lo
>   CXX      google/protobuf/compiler/subprocess.lo
>   CXX      google/protobuf/compiler/cpp/cpp_enum_field.lo
>   CXX      google/protobuf/compiler/cpp/cpp_generator.lo
>   CXX      google/protobuf/compiler/cpp/cpp_file.lo
>   CXX      google/protobuf/compiler/cpp/cpp_field.lo
>   CXX      google/protobuf/compiler/cpp/cpp_extension.lo
>   CXX      google/protobuf/compiler/cpp/cpp_map_field.lo
>   CXX      google/protobuf/compiler/cpp/cpp_helpers.lo
>   CXX      google/protobuf/compiler/cpp/cpp_message_field.lo
>   CXX      google/protobuf/compiler/cpp/cpp_padding_optimizer.lo
>   CXX      google/protobuf/compiler/cpp/cpp_primitive_field.lo
>   CXX      google/protobuf/compiler/cpp/cpp_service.lo
>   CXX      google/protobuf/compiler/cpp/cpp_string_field.lo
>   CXX      google/protobuf/compiler/cpp/cpp_message.lo
>   CXX      google/protobuf/compiler/java/java_enum_field.lo
>   CXX      google/protobuf/compiler/java/java_enum.lo
>   CXX      google/protobuf/compiler/java/java_enum_lite.lo
>   CXX      google/protobuf/compiler/java/java_context.lo
>   CXX      google/protobuf/compiler/java/java_enum_field_lite.lo
>   CXX      google/protobuf/compiler/java/java_extension.lo
>   CXX      google/protobuf/compiler/java/java_generator_factory.lo
>   CXX      google/protobuf/compiler/java/java_file.lo
>   CXX      google/protobuf/compiler/java/java_extension_lite.lo
>   CXX      google/protobuf/compiler/java/java_generator.lo
>   CXX      google/protobuf/compiler/java/java_field.lo
>   CXX      google/protobuf/compiler/java/java_helpers.lo
>   CXX      google/protobuf/compiler/java/java_map_field.lo
>   CXX      google/protobuf/compiler/java/java_map_field_lite.lo
>   CXX      google/protobuf/compiler/java/java_message.lo
>   CXX      google/protobuf/compiler/java/java_message_lite.lo
>   CXX      google/protobuf/compiler/java/java_message_builder.lo
>   CXX      google/protobuf/compiler/java/java_message_field_lite.lo
>   CXX      google/protobuf/compiler/java/java_name_resolver.lo
>   CXX      google/protobuf/compiler/java/java_message_field.lo
>   CXX      google/protobuf/compiler/java/java_message_builder_lite.lo
>   CXX      google/protobuf/compiler/java/java_primitive_field.lo
>   CXX      google/protobuf/compiler/java/java_shared_code_generator.lo
>   CXX      google/protobuf/compiler/java/java_primitive_field_lite.lo
>   CXX      google/protobuf/compiler/java/java_service.lo
>   CXX      google/protobuf/compiler/java/java_string_field.lo
>   CXX      google/protobuf/compiler/java/java_doc_comment.lo
>   CXX      google/protobuf/compiler/java/java_string_field_lite.lo
>   CXX      google/protobuf/compiler/js/js_generator.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_enum.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_enum_field.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_extension.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_field.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_file.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_helpers.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_message.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_generator.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_map_field.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_message_field.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_oneof.lo
>   CXX      google/protobuf/compiler/objectivec/objectivec_primitive_field.lo
>   CXX      google/protobuf/compiler/python/python_generator.lo
>   CXX      google/protobuf/compiler/csharp/csharp_doc_comment.lo
>   CXX      google/protobuf/compiler/ruby/ruby_generator.lo
>   CXX      google/protobuf/compiler/csharp/csharp_enum_field.lo
>   CXX      google/protobuf/compiler/csharp/csharp_enum.lo
>   CXX      google/protobuf/compiler/php/php_generator.lo
>   CXX      google/protobuf/compiler/csharp/csharp_helpers.lo
>   CXX      google/protobuf/compiler/csharp/csharp_generator.lo
>   CXX      google/protobuf/compiler/csharp/csharp_field_base.lo
>   CXX      google/protobuf/compiler/csharp/csharp_map_field.lo
>   CXX      google/protobuf/compiler/csharp/csharp_message.lo
>   CXX      google/protobuf/compiler/csharp/csharp_message_field.lo
>   CXX      google/protobuf/compiler/csharp/csharp_primitive_field.lo
>   CXX      google/protobuf/compiler/csharp/csharp_repeated_primitive_field.lo
>   CXX      google/protobuf/compiler/csharp/csharp_repeated_message_field.lo
>   CXX      google/protobuf/compiler/csharp/csharp_repeated_enum_field.lo
>   CXX      google/protobuf/compiler/csharp/csharp_reflection_class.lo
>   CXX      google/protobuf/compiler/csharp/csharp_source_generator_base.lo
>   CXX      google/protobuf/compiler/main.o
>   CXX      google/protobuf/compiler/csharp/csharp_wrapper_field.lo
> ```

You can try `make install`; sometimes multi-threaded builds can have problems, such as running out of memory.

We could remove the `ngraph-bridge` dependency for users who don't need the Python interface. But otherwise, everything is required.

**Comment by mlayou** [comment]
Thank you the install has worked now!

Just for reference, I had to also install `libomp5 `and `libomp-dev` for the build to finally complete.

`sudo apt install libomp5 libomp-dev`
