### ISSUE TITLE
Question about mechanics of the he-transformer library

### ISSUE THREAD

**Issue by mlayou** [IntelAI/he-transformer#40]
Hi, 

The purpose of this question is to understand the overall structure of the he-transformer library, and specifically how he-transformer modifies a regular tensor into one that is capable of computing homomorphically on encrypted data.

In line 51-52 in code below, a new `config` is defined (possibly with a `HE-SEAL backend` to enable homomorphic encryption), and a tensor flow session is constructed from that `config`. 

It is not clear, however, how the new tensor (from line 52) interacts with the SEAL library to replace regular operations with homomorphic ones. Can you indicate what parts of the he-transformer library are used to do that? 

https://github.com/IntelAI/he-transformer/blob/49879416a5b659edc1ca5b31493bc659685ae483/examples/MNIST/test.py#L43-L55

**Comment by fboemer** [comment]
The ngraph-tensorflow bridge is used to turn the TF graph into an ngraph function. 

This function is executed by the `HESealExecutable` (https://github.com/IntelAI/he-transformer/blob/master/src/seal/he_seal_executable.cpp#L1145-L1151), which maps , e.g. `ngraph::op::Multiply` to the `seal` multiply kernel in https://github.com/IntelAI/he-transformer/blob/master/src/seal/kernel/multiply_seal.cpp

**Comment by mlayou** [comment]
Thanks for the explanation. Does the newly-created ngraph function call the methods of the `HESealExecutable` object?

The `HESealBackend::compile` method [(see code here)](https://github.com/IntelAI/he-transformer/blob/49879416a5b659edc1ca5b31493bc659685ae483/src/seal/he_seal_backend.cpp#L217-L249) returns a `HESealExecutable` object. I assume, when the `HESealBackend` is created and configured (through `HESealBackend::compile`), the `HESealExecutable` object is instantiated along with it, and the latter is used to map the original Plaintext tensor to one that supports Ciphertext arguments. Is that how it works?

If I'm not mistaken, `he-transformer` currently supports only plaintext tensors (i.e., tensors with plaintext parameters/weights/biases) for ciphertext arguments. Can `he-transformer` be used to create ciphertext tensors (i.e., with encrypted parameters) for plaintext data inputs?

**Comment by mlayou** [comment]
As far as I understand, `he-transformer` currently supports only plaintext tensors (i.e., tensors with plaintext weights/biases) for ciphertext arguments. Can `he-transformer` be used to create ciphertext tensors (i.e., with encrypted weights/biases) for plaintext/ciphertext data inputs?

**Comment by fboemer** [comment]
Yes, we do support ciphertext data inputs, that's the main feature of this project. Input data can be encrypted in one of two ways:

1) In server-client approach; the HESealClient creates an encrypted ciphertext [here](https://github.com/IntelAI/he-transformer/blob/49879416a5b659edc1ca5b31493bc659685ae483/src/seal/he_seal_client.cpp#L201-L204) when `encrypt_tensor == true`.

2) In server-only approach; the data is encrypted [here](https://github.com/IntelAI/he-transformer/blob/49879416a5b659edc1ca5b31493bc659685ae483/src/seal/he_seal_executable.cpp#L690-L705)

**Comment by mlayou** [comment]
If you run the following in client-server mode, does the library keep the client data in plaintext and encrypt the weights of the neural network? 

If this is the case, since the params of the neural net are encrypted, the output of the neural network, as well as all the intermediary values, should be encrypted, although the input was in plaintext. 

Is this an accurate understanding of how he-transformer works?

**Server-side**
```
python test.py --backend=HE_SEAL \
               --model_file=models/cryptonets.pb \
               --enable_client=true \
               --encryption_parameters=$HE_TRANSFORMER/configs/he_seal_ckks_config_N13_L8.json
```
**Client-side**
```
python pyclient_mnist.py   --batch_size=10 \
                           --encrypt_data_str=plain
```

**Comment by mlayou** [comment]
Can he-transformer protect the confidentiality of the neural network parameters (weights & biases)?

For more context, assume the following scenario. The neural network is owned by the server, who wants to run the neural network on the client's machine. Can he do that while protecting the NN's parameters from the client? 

Obviously, because the output of the NN is encrypted, it has to be returned to the server so he can decrypt. 

Thanks.

**Comment by mlayou** [comment]
Another observation. 

I was running the MNIST example in client-server mode, with encryption enabled on the client side. Since encryption is enabled, he-transformer updates the annotations of the NNet to transform it to a ciphertext tensor. However, not everything in the new tensor is encrypted. 
In particular constants (which I assume refer to the weights and biases of the network) are left in plaintext. Perhaps, that design decision was made for performance reasons (since adding a ciphertext to a plaintext is more computationally-efficient and results in less noise than adding two ciphertexts). Is this why constants in the new tensor were left non encrypted?

Following are some logs showing [Constant_1099] left in the clear, while the output of subsequent operation [Add_842] is encrypted although one of its operands [Constant_1099] is in the clear : 

```
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 773	[ Constant_1099 ]
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 777	Constant shape Shape{1, 10}
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 819	Get output packing / encrypted
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 826	encrypted_out 0
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 827	packed_out 0
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 831	Creating output tensor with shape Shape{1, 10}
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 876	Constant_1099 took 0ms

[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 773	[ Add_842 ]
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 819	Get output packing / encrypted
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 826	encrypted_out 1
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 827	packed_out 1
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 831	Creating output tensor with shape Shape{10, 10}
[INFO] 2020-05-21T17:58:39z src/seal/he_seal_executable.cpp 876	Add_842 took 1ms
```

**Comment by mlayou** [comment]
Is it possible to have a fully-encrypted tensor even if the client input is in plaintext?

**Comment by fboemer** [comment]
> If you run the following in client-server mode, does the library keep the client data in plaintext and encrypt the weights of the neural network?
> 
> If this is the case, since the params of the neural net are encrypted, the output of the neural network, as well as all the intermediary values, should be encrypted, although the input was in plaintext.
> 
> Is this an accurate understanding of how he-transformer works?
> 
> **Server-side**
> 
> ```
> python test.py --backend=HE_SEAL \
>                --model_file=models/cryptonets.pb \
>                --enable_client=true \
>                --encryption_parameters=$HE_TRANSFORMER/configs/he_seal_ckks_config_N13_L8.json
> ```
> 
> **Client-side**
> 
> ```
> python pyclient_mnist.py   --batch_size=10 \
>                            --encrypt_data_str=plain
> ```

We no longer support encrypting the network parameters. The code you posted will keep the data plaintext, due to `--encrypt_data_str=plain` in the client code.

**Comment by fboemer** [comment]
> Can he-transformer protect the confidentiality of the neural network parameters (weights & biases)?
> 
> For more context, assume the following scenario. The neural network is owned by the server, who wants to run the neural network on the client's machine. Can he do that while protecting the NN's parameters from the client?
> 
> Obviously, because the output of the NN is encrypted, it has to be returned to the server so he can decrypt.
> 
> Thanks.
Encrypting the neural network parameters is a way to protect the model weights. However, we don't support this functionality, mostly due to an even larger memory/runtime overhead.

You're right, with this approach, the NN output is encrypted, and would have to be returned to the server for decryption.

**Comment by fboemer** [comment]
> Is it possible to have a fully-encrypted tensor even if the client input is in plaintext?
No; the intended use case is that the client provides encrypted input. Plaintext client input is used mostly for debugging.

**Comment by mlayou** [comment]
Thank you!
